version: '3'

services: 

  app:
    build: .
    container_name: ms-subscribe-app
    entrypoint: .docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes: 
      - .:/home/node/app
    networks:
      - default
      - rabbitmq_saas-store

  db:
    image: mysql:5.7
    container_name: ms-subscribe-db
    restart: always
    tty: true
    ports: 
      - 3306
    volumes: 
      - .mysqldata:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=subscription_service_development
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root

networks:
  default:
    driver: bridge
  rabbitmq_saas-store:
    external: true
  # redis_saas-store:
  #   external: true
