name: Build Admin Panel (DEV)

on:
  push:
    paths:
      - 'packages/admin-panel/**'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: cd e chmod
        run: cd packages/admin-panel/ && chmod +x .docker/entrypoint.sh && docker network create rabbitmq_saas-store && docker-compose up -d

      - name: Rodando os testes
        run: yarn && yarn test