name: Build Payment MS (DEV)

on:
  push:
    paths:
      - 'packages/payment-ms/**'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build Aplication
        run: cd packages/payment-ms/ && sls offline start
